spring.application.name=siscar-backend

#Connexion a SQL Server
spring.datasource.url=jdbc:sqlserver://localhost\\SQLEXPRESS;databaseName=SiscarV2;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=Admin1234!
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Puerto del backend
server.port=8080